// Autogenerated by discovery-gen v0.x.
module google_api.sheets.spreadsheets.sheets.d_methods;

public import std.typecons: Nullable, Ternary, apply, nullable; ///

import google_api.d.attributes;
import google_api.d.http: HttpMethod;
import t = google_api.sheets.d_types;

/// Copies a single sheet from a spreadsheet to another spreadsheet. Returns the properties of the newly created sheet.
struct CopyTo {
	enum restHttpMethod = HttpMethod.post; ///
	enum restPath = [`v4/spreadsheets/`, `/sheets/`, `:copyTo`]; ///
	alias Request = t.CopySheetToAnotherSpreadsheetRequest; ///
	alias Response = t.SheetProperties; ///
}
