// Autogenerated by discovery-gen v0.x.
module google_api.sheets.spreadsheets.developer_metadata.d_methods;

public import std.typecons: Nullable, Ternary, apply, nullable; ///

import google_api.d.attributes;
import google_api.d.http: HttpMethod;
import t = google_api.sheets.d_types;

/// Returns the developer metadata with the specified ID. The caller must specify the spreadsheet ID and the developer metadata's unique metadataId.
struct Get {
	enum restHttpMethod = HttpMethod.get; ///
	enum restPath = [`v4/spreadsheets/`, `/developerMetadata/`, ``]; ///
	alias Response = t.DeveloperMetadata; ///
}

/// Returns all developer metadata matching the specified DataFilter. If the provided DataFilter represents a DeveloperMetadataLookup object, this will return all DeveloperMetadata entries selected by it. If the DataFilter represents a location in a spreadsheet, this will return all developer metadata associated with locations intersecting that region.
struct Search {
	enum restHttpMethod = HttpMethod.post; ///
	enum restPath = [`v4/spreadsheets/`, `/developerMetadata:search`]; ///
	alias Request = t.SearchDeveloperMetadataRequest; ///
	alias Response = t.SearchDeveloperMetadataResponse; ///
}
